### ISSUE TITLE
ORCID validation 

### ISSUE THREAD

**Issue by mpfl** [au-research/raido#21]
Submitted on behalf of UNDA

**What happens:**

When editing a RAiD's metadata, trying to add an ORCID iD with an X in the checksum position (e.g. https://orcid.org/0009-0001-8177-319X) is rejected as invalid, with an error message of:

`contributors[0].id - Contributor ORCID should have the format https://orcid.org/0000-0000-0000-0000.`

I have just replicated this behaviour successfully in demo by  entering `0009-0001-8177-319X` into the Lead Contributor ORCID field and clicking Mint RAiD.

**Expected behaviour:**

The metadata entry form should accept ORCID iDs with an X gracefully.

**Comment by ardc-shorn** [comment]
reproduced in demo

introduced for external service existence validation: 

which I think was implemented to eliminate a “security” issue reported by github?

I recall something about it not liking that we were using directly calling an url that was being provided as input from the API

https://github.com/au-research/raido/commit/0bcc643dd84b0f07fdf76d87e44141aa9fdbb464

quick fix: just update the regex

long fix:

we’ve got two separate, duplicate bits of logic that check the orcid id format, one of which doesn’t understand check digits

refactor to one block

could use an integration test, I reckon

deploy:

do it on the 1.2 branch, “hotfix” deploy it whenever is convenient

no api changes, no ui changes, no DB changes, no functionality changes except fixing the defect

I don’t think it needs any external comms, should probably do it in maintenance window though

add a link to the fixed issue in the changelog on the 1.2 branch

back-port the fix to main branch

add to changelog

consider implementing the “long fix” instead

**Comment by robleney-ardc** [comment]
[The fix](a79e59f0bbd036179dea6c37a58b35b766bf8e66) for this has been released to production.
