### ISSUE TITLE
Exclude software version from the repo name

### ISSUE THREAD

**Issue by arnikz** [au-research/raido#4]
I agree with the statement in the [readme.md](/au-research/raido-v2/blob/da968be56de9e53ec8f6c3bdffb38f2aedde3cbb/readme.md):
_It's called "v2" because initially it was called raid-v2 because there was a v1. Should've just called it "raido" - oh well._

Proposition:
1. Rename repo `raido-v2` to `raido`.
2. Create GH [releases](/au-research/raido-v2/releases) following [semantic versioning](https://semver.org/) (e.g., begin with `v0.1.0`)

**Comment by ardc-shorn** [comment]
1.) It's not really the version, just a unique descriptive name.
Regardless, the `v2` part was a mistake and we should fix it.
We will change the repo name to `raido` after @robleney-ardc has finished creating prod infra - work is still in progress on that, no ETA.

2.) We're not planning to use GH releases for operating the Raido software for Oceania (that is being handled through AWS CodeBuild/CodePipeline processes managed out of the private AWS-centric repo).
Happy to use GH releases for the purpose of "releasing" the software for other Raid agencies to use as the basis for building their software, but not planning to do that for a while.

**Comment by ardc-shorn** [comment]
Repo has been renamed to `raido`.
Note that old links to `raido-v2` will redirecto to `raido` - existing git repositories using `raido-v2` should continue to work, but you should re-set your origin via `git remote set-url origin`.

**Comment by ardc-shorn** [comment]
* To show current `origin`: `git remote -v`
* To set new `origin`: `git remote set-url origin https://github.com/au-research/raido.git`

**Comment by ardc-shorn** [comment]
I've also changed the config directory that the code uses from `~/.config/raido-v2` to `~/.config/raido`.
The codebase still searches the old location for the moment, but that will be dropped eventually, see https://github.com/au-research/raido/blob/cc153bc478c11f6d9233cb22dca3fcfa20565f4d/api-svc/spring/src/main/java/raido/apisvc/spring/config/ApiConfig.java#L66.
