### ISSUE TITLE
Keep a CHANGELOG

### ISSUE THREAD

**Issue by arnikz** [au-research/raido#5]
Let's make sure to communicate notable changes in a release (`CHANGELOG.md`) to the users and contributors. Every release should have relevant entry in change log. For example, what is the current set of functionalities included in the software (related to #4)? See some [best practices](https://keepachangelog.com/en/1.0.0/).

**Comment by ardc-shorn** [comment]
Will create a changelog file after first release of Raido to prod.

The target audience for the changelog will be:
1. Customers of Raido service (i.e. universities/other institutions and API integrators) - either directly or indirectly where some "customer communications" process will use the changelog as input.
2. ARDC Change control board - for satisfying the required ARDC DevOps change control process.

**Comment by ardc-shorn** [comment]
https://github.com/au-research/raido/blob/main/changelog.md
